baseURL = 'https://plrefjp.github.io/quickstart/'
languageCode = 'ja-jp'
title = 'Programming Languages'
theme = 'mytheme'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Lexical Structure'
pageRef = '/lexical_structure'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
custom_css = ["css/hamburger-menu.css", "css/lexical_structure.css", "css/syntax.css"]
